//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaSoft.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmaciaEntities : DbContext
    {
        public FarmaciaEntities()
            : base("name=FarmaciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<Recurso> Recurso { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Tipo_Movimiento> Tipo_Movimiento { get; set; }
        public virtual DbSet<Tipo_Presentacion> Tipo_Presentacion { get; set; }
        public virtual DbSet<Tipo_Recurso> Tipo_Recurso { get; set; }
    }
}
