//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idTipoMovimiento { get; set; }
    
        public virtual Tipo_Movimiento Tipo_Movimiento { get; set; }
    }
}
