//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recurso()
        {
            this.Stock = new HashSet<Stock>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public float precio { get; set; }
        public int stockMinimo { get; set; }
        public int idTipoRecurso { get; set; }
        public int idArea { get; set; }
        public Nullable<int> idTipoPresentacion { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Tipo_Presentacion Tipo_Presentacion { get; set; }
        public virtual Tipo_Recurso Tipo_Recurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
