//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id { get; set; }
        public int idRecurso { get; set; }
        public int cantidad { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
    
        public virtual Recurso Recurso { get; set; }
    }
}
